# EDIT THIS FILE TO CUSTOMIZE THE HANDBOOK

# Inherit config from base
INHERIT: ./base.yml

# Project Information
site_name: "CognitiveArchitectHandbookName"
site_url: "https://pages.github.ibm.com/CognitiveArchitectRepoParent/CognitiveArchitectRepoDir/"
site_description: "CognitiveArchitectSiteDescription"
site_author: "CognitiveArchitectSiteAuthor"

# Repository Information
repo_name: 'CognitiveArchitectRepoParent/CognitiveArchitectRepoDir'
repo_url: 'https://github.ibm.com/CognitiveArchitectRepoParent/CognitiveArchitectRepoDir'

# Specify a navigation structure for the first page, uses awesome-pages
# https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin
nav:
    - Intro: index.md
    - ...

# Copyright
copyright: <a href="/about/">CognitiveArchitectSiteAuthor</a>.

# Extra links as icons at the bottom of the page
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.ibm.com/oic/
    - icon: fontawesome/solid/globe
      link: https://www.ibm.com/

# Configure the Markdown extensions for magic links
markdown_extensions:
  - admonition:
  - attr_list:
  - def_list:
  - tables:
  - abbr:
  - footnotes:
  - md_in_html:
  - meta
  - toc:
      permalink: true
      toc_depth: 4
  - smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - pymdownx.critic:
  - pymdownx.superfences:
     preserve_tabs: true
     custom_fences:
       - name: mermaid
         class: mermaid
         format: !!python/name:pymdownx.superfences.fence_code_format
       - name: flow
         class: uml-flowchart
         format: !!python/name:pymdownx.superfences.fence_code_format
       - name: sequence
         class: uml-sequence-diagram
         format: !!python/name:pymdownx.superfences.fence_code_format
       - name: math
         class: arithmatex
         format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.highlight:
      css_class: codehilite
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite:
        custom_inline:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.inline_mathjax_format
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: true
      nbsp: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.arithmatex:
  - pymdownx.mark:
  - pymdownx.striphtml:
  - pymdownx.snippets:
      base_path: docs/src/markdown/_snippets
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.details:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.magiclink:
      provider: 'github'
      repo_url_shortener: true
      repo_url_shorthand: false
      social_url_shorthand: true
      user: CognitiveArchitectIBMGitHub
      repo: CognitiveArchitectRepoParent/CognitiveArchitectRepoDir

# Configure the PDF export plugin
plugins:
  - search
  - inline-svg
  - table-reader
  - git-revision-date-localized:
      fallback_to_build_date: true
  - git-authors
  - awesome-pages:
      filename: .pages
      collapse_single_pages: false
      strict: false
  - minify:
      minify_html: true
  - blog:
      format: "(%m/%d/%y)"
      folder: "blog"
      articles: 10                 # How many do we display
      display-article-date: true   #
      display-more-articles: true  # Can we display the previous articles section, or is it better if we hide it?
  - pdf-export:
      verbose: false
      media_type: print
      enabled_if_env: ENABLE_PDF_EXPORT
      combined: false
  - with-pdf: # This creates a single PDF document for the whole site
      author: CognitiveArchitectSiteAuthor
      copyright: Copyright &copy; CognitiveArchitectSiteAuthor
      cover: true
      back_cover: false
      #
      cover_title: CognitiveArchitectHandbookName
      cover_subtitle: CognitiveArchitectSiteDescription
      cover_logo: 'img/logo-ibm.png'
      #custom_template_path: TEMPLATES PATH
      #
      toc_title: Contents
      # heading_shift: false
      toc_level: 2
      #ordered_chapter_level: 2
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      #
      exclude_pages:
          - '99.about/'
          - 'blog'
      #    - 'appendix/contribute/'
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      #two_columns_level: 3
      #
      # render_js: true
      #headless_chrome_path: headless-chromium
      #
      output_path: ./pdf/CognitiveArchitectRepoDir.pdf
      enabled_if_env: ENABLE_PDF_EXPORT
      #
      debug_html: true
      #show_anchors: true
      verbose: false
